### ISSUE TITLE
404 Not Found: @ember-decorators/argument@latest

### ISSUE THREAD

**Issue by urbany** [ember-decorators/argument#19]
Hi,

Failed to install on npm@5.5.1:

```
Command failed: npm install --save-dev --loglevel error @ember-decorators/argument
npm ERR! code E404
npm ERR! 404 Not Found: @ember-decorators/argument@latest
```

**Comment by pzuraq** [comment]
We just changed the name and haven't yet published the package, sorry about that! I'm pushing it out today along with a fix for that other problem we discovered with validations, will update when it's out

**Comment by pzuraq** [comment]
Package has been published under the new name! 😄
