### ISSUE TITLE
Only validate components with validations

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/argument#27]
It is not explicitly documented, but judging from the errors I'm getting and a quick glance at the code, it looks like [*all component declarations* are transformed to extend `ValidatedComponent`](https://github.com/ember-decorators/argument/blob/fd1639533b955f4dcb9c9ccb9b7098f2bc7df539/lib/validated-component-transform/index.js#L11-L18) (cool idea btw!), which then in turn checks [whether all passed args are defined as a validation, class name or attribute binding](https://github.com/ember-decorators/argument/blob/fd1639533b955f4dcb9c9ccb9b7098f2bc7df539/addon/-debug/validated-component.js#L39).

I just tried installing this addon in a pre-existing app with close to 600 components. I can't possibly annotate all these components in one go with the appropriate decorators.

It would be super useful, if there'd be an option to disable validation as a whole for components without validation decorators.

Open for a PR?

**Comment by pzuraq** [comment]
So there is actually an option for ember-cli, it just isn’t documented and hasn’t been updated since the name change: https://github.com/ember-decorators/argument/blob/fd1639533b955f4dcb9c9ccb9b7098f2bc7df539/index.js#L113

I think we’ll need to bump to v0.8 to update it, ember-cli options should be under `@ember-decorators/argument` instead of `emberArgumentDecorators`, but it should be usable now. Also definitely need to add docs!

**Comment by pzuraq** [comment]
Also should note that the transform applies only to the immediate parent, so addons will still be able to get the benefits of it even if your app can’t. This is why it’s on by default, to encourage people to define their arguments rigorously 😄

**Comment by buschtoens** [comment]
This option would disable validation for all components, right? I was thinking about disabling validation only for components that have no `@argument` decorators, so that I can slowly migrate all 600 components (that all live in the same app namespace).

**Comment by pzuraq** [comment]
Yes, unfortunately that’s a bit more tricky. How do we distinguish if a component has validations or not?

I suppose there are two options here, either A. Write a transform that is somehow aware of this context (maybe looks for import of `@argument`?) or B. Export validated component so users can use it directly. If we can come up with a good heuristic I think option A would be fine, I’m open to either though

**Comment by buschtoens** [comment]
https://github.com/ember-decorators/argument/blob/fd1639533b955f4dcb9c9ccb9b7098f2bc7df539/addon/-debug/validated-component.js#L33

Can't we just do something like:

```js
const validations = getValidationsFor(prototype) || {};
if (options.ignoreComponentsWithoutValidations && Object.keys(validations).length === 0) {
  return instance;
}
```

Wouldn't this effectively skip components that have no validations defined on them?

**Comment by pzuraq** [comment]
That could work too, probably better than writing a weird transform 😜 the only thing I can see being an issue is if a component shouldn’t have arguments, there’s no way to really enforce that, but I think that’s fine. Feel free to PR it!

**Comment by buschtoens** [comment]
> if a component shouldn’t have arguments, there’s no way to really enforce that

Yeppa, that'll be the trade-off during the transition phase.

Are you okay with `ignoreComponentsWithoutValidations` or do you think there's a better name? :smile:

**Comment by pzuraq** [comment]
I can't think of anything better at the moment, so let's go for it. You can see that we're using `ember-get-config` in the addon: https://github.com/ember-decorators/argument/blob/5da4de19046d1d8d7d78d3b90a6f8d336e8f2748/addon/index.js#L15

Same issue as before, it's on the old key `emberArgumentDecorators` but should be changed to reflect the new name of the repo. I think doing the same, `@ember-decorators/argument` would be fine, but I'm not sure if there are super strong conventions around runtime addon options yet..

**Comment by buschtoens** [comment]
I'll change all occurrences of `emberArgumentDecorators` to `emberDecoratorsArgument` with my PR. Is the key okay or do rather want `emberDecorators.argument`?
