### ISSUE TITLE
enum / values validator

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/argument#30]
I often write components that take specific string values as configuration parameters. For example, an icon component might take 4 different, pre-defined, named sizes, like `small`, `medium`, `large`, `extra-large`.

I'd like a validator that only allows these specific values, for instance:

```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { values } from '@ember-decorators/argument/type';

export default class IconComponent extends Component {
  @argument
  @values('small', 'medium', 'large', 'extra-large')
  size = 'medium';
}
```

I am open to name suggestions and would love to submit a PR!

**Comment by pzuraq** [comment]
I'm actually trying to match up the types Typescript right now, and two of the primitive types we're missing are `enum` and `tuple`. I think they would work well as validator functions that integrate with the `@type` decorator:

```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { type, enum, tuple } from '@ember-decorators/argument/type';
import { immutable } from '@ember-decorators/argument/validation';

export default class IconComponent extends Component {
  @argument
  @type(enum('small', 'medium', 'large', 'extra-large'))
  @immutable
  size = 'medium';

  @argument
  @type(tuple('string', 'number'))
  foo = ['bar', 2];
}
```

The nice thing about doing it this way is validators can actually be used externally to define types, much like you would do in Typescript:

```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { type, enum, tuple } from '@ember-decorators/argument/type';
import { immutable } from '@ember-decorators/argument/validation';

const Sizes = enum('small', 'medium', 'large', 'extra-large');

export default class IconComponent extends Component {
  @argument
  @type(Sizes)
  @immutable
  size = 'medium';
}
```

**Comment by buschtoens** [comment]
I was thinking about enums the other day. The problem with enums, as used in TypeScript and other programming languages, is that they are basically just fancy integers. 

```ts
enum Color { Red, Green, Blue }
console.log(Color.Green); // => 1
```

This is not what I originally had in mind for this issue, as this is not ideal when interfacing with components through templates, especially for consumers of addons. You either have to pass the numeric value, which would give you no clue as to what it does, or you have to make the `Color` type available in the scope of the template:

```js
import { enum } from '@ember-decorators/argument/type';

export const Color = enum('Red', 'Green', 'Blue');
```

```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument'; 
import { type } from '@ember-decorators/argument/type'; 
import { immutable } from '@ember-decorators/argument/validation'; 
import { Color } from 'foo-app/types'; 

export default class FooComponent extends Component {
  @immutable
  Color = Color;

  @argument
  @type(Color)
  color;
}
```

```hbs
{{foo-component color=2}} 
{{foo-component color=Color.Red}} 
```

I don't like either solution really much. We could think about adding an `{{enum}}` template helper, that aids in looking up an enum, but that's also besides the point and makes consuming an addon complex.

AFAIK the conventional ember-way was / is to pass string values. While I really like the enum type and think that we should definitely implement it (be it for TS-compatibility only), a similar type that explicitly accepts a set of concrete values, should be added as well.

```js
import { values } from '@ember-decorators/argument/type';

export const Color = values('Red', 'Green', 'Blue');
```

Do you have a better name than `values`?

---

Another thing: `values` and especially `enum` should allow some form of reflection.

For `enum` I'd like to copy or stay close to the semantics and syntax of [TypeScript's Enum](https://www.typescriptlang.org/docs/handbook/basic-types.html#enum), if possible, so that the user can lookup the numeric value for an enumeral and the other way around.

**Comment by pzuraq** [comment]
Agreed that both would be helpful here, and we should keep `enum` as close to TS semantics as possible. I think we could call the `values` helper `oneOf` which would be inline with our naming scheme currently and read like English (it's one-of these values) but I'm open to either.

**Comment by allthesignals** [comment]
So what I'm hearing is that we want a `oneOf` helper that validates passage of any one _string_ type value. ~Would this need to compose with other validators? For example:~

(EDIT: I realize that's just the `unionOf` helper)

```javascript
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { oneOf, type, shapeOf } from '@ember-decorators/argument/type';

export default class IconComponent extends Component {
  @argument
  @oneOf(shapeOf({ key: type('string') }), shapeOf({ anotherKey: type('string') }))
  size = { key: 'bananas' };
}
```

Separately, I'm not sure I follow where we've settled on the way forward with an `enum` helper, which seems to be more about mapping numeric and string values. When I found this issue, I wasn't thinking about that sort of validation, but I can see how it's related and useful.
