### ISSUE TITLE
No initial value in production build

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/argument#38]
When I build a production version of my app and try to access an (in-repo) engine that uses `@ember-decorators/argument`, I receive this error:

```
Uncaught Error: Could not find module `@ember-decorators/argument/type` imported from `auswertung-top/components/app-header/component`
```

Seems like the imports are not properly stripped?

**Comment by buschtoens** [comment]
I found the culprit:

```js
import { unionOf as _unionOf } from '@ember-decorators/argument/type';
```

This was my hack to circumvent https://github.com/ember-cli/babel-plugin-filter-imports/issues/30, but apparently this causes the import to just not get removed.

I've changed it to this:

```js
import { unionOf } from '@ember-decorators/argument/type';

const _unionOf = (...types) => unionOf(...types);

export const optional = type => _unionOf(type, undefined, null);
```

Now the import gets removed. So I guess this is an upstream bug with [babel-plugin-filter-imports](https://github.com/ember-cli/babel-plugin-filter-imports). There's still other stuff going wrong, so I'll keep this open, while I try to pinpoint it.

**Comment by buschtoens** [comment]
Found the problem. Why was this line put there?

https://github.com/ember-decorators/argument/blob/9839f9eb11aa22f74439a929289c14b7c7c14c1e/addon/index.js#L22

In dev mode `desc.initializer` is always `undefined` (for the property in question).

![image](https://user-images.githubusercontent.com/834636/33255581-a93ca780-d34e-11e7-8bbb-d2d961bf043d.png)

Since `undefined !== null`, the following code path is executed:

https://github.com/ember-decorators/argument/blob/9839f9eb11aa22f74439a929289c14b7c7c14c1e/addon/index.js#L24-L42

In prod mode `desc.initializer` is `null` (for reasons that probably shall remain a mystery :joy: ).

Since `null === null` the code path linked above is *not* executed, which is why the property in question is `undefined`, after the `construtor()` ran.

![image](https://user-images.githubusercontent.com/834636/33255771-65bd715a-d34f-11e7-817b-b451978fdd58.png)

```js
function AppHeaderComponent() {
  _classCallCheck(this, AppHeaderComponent);

  // this.startDate => undefined

  // didReceiveAttrs()
  var _this = _possibleConstructorReturn(this, (AppHeaderComponent.__proto__ || Object.getPrototypeOf(AppHeaderComponent)).call(this));

  // this.startDate => LocalDate { ... }

  // @argument decorator is applied
  _initDefineProp(_this, 'startDate', _descriptor3, _this);

  // this.startDate => undefined

  console.log('constructor()', _this.startDate);
  return _this;
}
```

Simply removing this `if` statement appears to fix everything, while not introducing any new bugs, at least as far as I can see.

https://github.com/ember-decorators/argument/blob/9839f9eb11aa22f74439a929289c14b7c7c14c1e/addon/index.js#L22

**Comment by pzuraq** [comment]
`desc.initializer` should be null when the property does not have an initial value set at all:

```js
class Foo {
  bar; // no initializer

  baz = null; // initializer === () => null;
}
```

I think the initial reason I added that `return` was because I believed that if the initializer itself was null/falsey, no value would be assigned at all in the object's constructor, which would mean there was no reason for us to do any of the logic in `argument`. If that's true, everything should Just Work.

Apparently it's not 😅 Can you post the code for the class that is causing these failures? I want to make sure we have the logic correct here.

**Comment by buschtoens** [comment]
```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';

export default class FooComponent extends Component {
  @argument
  stringWithDefault = 'defaultValue';

  @argument
  stringWithoutDefault;
}
```

```hbs
{{foo-component stringWithoutDefault="foo-bar"}}
```

In production mode `stringWithoutDefault` is just `undefined`.

This happens for regular apps, not just in-repo-engines. What lead me to believe that this was related to in-repo-engines was a combination of multiple bugs (including https://github.com/ember-cli/babel-plugin-filter-imports/issues/30 and #41 among others).

**Comment by km-smith** [comment]
Is anyone actively working on a fix for this? Currently, my app has all of these awesome decorators commented out so our production builds work.

**Comment by buschtoens** [comment]
I was gonna debug it today, but other stuff got in the way. 🙈

I have a  _massive_ interest in getting this fixed, can't promise it though yet, since it _might_ be over my head (yet).

**Comment by pzuraq** [comment]
Bugfixed published in 0.8.4, let me know if you still have issues!

**Comment by olegstepura** [comment]
This happens to us right now with
```js
    "ember-cli": "3.10.1", 
    "@ember-decorators/argument": "0.8.21",
    "ember-decorators": "6.0.0",
```

The only fix I found was to set `disableCodeStripping` to `true`:
```js
    '@ember-decorators/argument': {
      disableCodeStripping: true,
    },
```

with  `disableCodeStripping` set to `false` we see those errors in browser console:
```
Could not find module `@ember-decorators/argument/type` imported from `...`
```

**Comment by VincentMolinie** [comment]
I had the exact same issue a few minutes ago
```js
    "ember-cli": "3.12.1",
    "ember-cli-babel": "7.19.0",
    "@ember-decorators/argument": "0.8.21",
```

I'm pretty sure you issue is here:
https://github.com/ember-decorators/argument/blob/10f4515c662ed4a35a798ea856755c012006c445/index.js#L66
Because you configure only if the filter imports is not already included
