### ISSUE TITLE
Default value for nullish arguments

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/argument#49]
From the README:

>  `@argument` declares a field as an argument of the component or object and optionally will assign a default value *unless* one is passed in or provided by a superclass.

I just ran into a scenario, where some array is externally provided through an ember-concurrency task like so:

```hbs
{{foo-component data=taskInstance.value}}
```

As long as the task did not succeed (i.e. is still running or failed) `taskInstance.value` is `null`.

In my component class I have some code like this:

```js
export default FooComponent extends Component {
  @argument
  data = [];

  @computed('data.[]')
  get transformedData() {
    return transformedData.map((x) => ...);
  }
}
```

Obviously, this codes breaks, since the default value `[]` will not be used as `null` is explicitly passed in. Assuming that I'm gonna access `data` in a lot of places, I would not want to go `(data || [])` (or with the [nullish coalescing operator](https://github.com/tc39/proposal-nullish-coalescing) `(data ?? [])`), but would like `@argument` to be configurable in a way that enables falling back to the default value, if the passed arg is nullish.

Do you think this is a good idea or should I rather create an intermediary computed property that implemented the nullish fallback?

If accepted, what API would be best? An extra decorator or a config option for for `@argument`?
And what name should the option / decorator have?

```js
export default FooComponent extends Component {
  @argument({ defaultIfNullish: true })
  data = [];

  @argument
  @defaultIfNullish
  data = [];
}
```

**Comment by pzuraq** [comment]
I decided to implement this as an option to `@argument` for now, I'm definitely open to making it a standalone decorator though. I'm personally bikeshedding about how the API works now a lot, wondering if it's solid or needs to be updated (like I mentioned to you offline the other day 😄) so we'll see.
