### ISSUE TITLE
Deprecation warning - Using the global version of DS is deprecated

### ISSUE THREAD

**Issue by fran-worley** [ember-decorators/argument#57]
We're getting 3 warnings about this ember-data deprecation:
```
DEPRECATION: Using the global version of DS is deprecated. Please either import the specific modules needed or `import DS from 'ember-data';`. [deprecation id: ember-data.global-ds]
```

Having done a search for use of `window.DS`, I believe this is the culprit:
https://github.com/ember-decorators/argument/blob/master/addon/-debug/utils/validation-decorator.js#L273-L275

**Comment by pzuraq** [comment]
Hmm, tricky. This is kind of a catch 22 because we don't want to add Ember Data as a dependency to this library, and the real Ember Data module transforms aren't out yet 🙃

I'll look into seeing if there's a way to suppress that error for the time being

**Comment by fran-worley** [comment]
You probably don't want a dependency just to manage this but this addon https://github.com/offirgolan/ember-require-module seems to be a solution...

I know that ember-cp-validations optionally hooks into ember-data but doesn't want to make it an addon so they use that addon to require it.
