### ISSUE TITLE
meta.peekDescriptors fails in Ember Canary

### ISSUE THREAD

**Issue by simonihmig** [ember-decorators/argument#64]
It seems [this line](https://github.com/ember-decorators/argument/blob/e9b81df514c0ef2b5cc4cead64911fb02be9bf07/addon/-debug/utils/validation-decorator.js#L203) is failing in latest canary. 

Example: https://travis-ci.org/kaliber5/ember-bootstrap/jobs/356845418#L1202 (this test is using ember-popper)

**Comment by pzuraq** [comment]
You aren’t actually running against canary, you need to upgrade to using ember-source-channel-urls. We should check to see what the last version of canary was that was published to bower, this could be a bug in ember-compatibility-helpers, but more likely the last one published was a version of 3.1 just before the ES5 getters work was done.

**Comment by simonihmig** [comment]
Ah ok, makes sense. I have that upgrade in a separate PR, will merge those and revisit this issue then. Thanks so far!

**Comment by simonihmig** [comment]
Confirmed, this does not occur with canary from the new source channels...
Sorry...

**Comment by pzuraq** [comment]
No worries, it’s totally not-obvious, ran into the same thing when upgrading myself 🙂
