### ISSUE TITLE
Does not work with TypeScript

### ISSUE THREAD

**Issue by alexlafroscia** [ember-decorators/argument#65]
I'm running into an issue where the decorators are not compatible with the way that property decorators work in TypeScript.

If you check out the [decorators documentation](http://www.typescriptlang.org/docs/handbook/decorators.html), there's a relevant bit here:

> A Property Descriptor is not provided as an argument to a property decorator due to how property decorators are initialized in TypeScript. 

Originally, I modified the validation decorator to ignore `desc` if it did not exist, but this forces the property to become immutable because there's no way to set `desc.writable`. Not sure if there's a good solution here, but I figured it was worth keeping track of since the `@ember-decorators` libraries are a very useful when working with TypeScript.

**Comment by pzuraq** [comment]
Hey! So this is definitely a known issue, based on the limitations in Typescript. It's actually part of the reason why this is not part of the "core" decorators (the other part being that there's going to be a lot of overlap with `@argument` and actual `@args`, and glimmer components, etc, so while it's super helpful for modern components unsure how it fits into the overall Ember story yet 😅)

We should keep this issue open to track it, and update as soon as TS updates their transforms to add support. Thanks for opening it!

**Comment by jordpo** [comment]
Any updates on TS support? Thanks!

**Comment by pzuraq** [comment]
Yes actually, based on the recent [class constructor update RFC](https://github.com/emberjs/rfcs/blob/master/text/0337-native-class-constructor-update.md) this library will no longer be needed at all for runtime. Once that RFC is implemented (my main focus right now) the behavior that `@argument` provides will be the default behavior in native classes, without decorators 😄 

This library will be updated to be 100% validation decorators only, which will be removed entirely in production builds. The validations provided here are really a weak subset of the validations provided by Typescript, so this library will _not_ attempt to support TS directly. The decorators may still work, but long term what we really want is to get type checking working directly in Glimmer templates. If we can get that, then you'll be able to use standard TS types to know whether an argument exists, whether it is required, what it's types are, etc.

Going to close this issue for now, thanks for reminding me!

**Comment by jordpo** [comment]
Awesome!

**Comment by flashios09** [comment]
hi @pzuraq,
sorry, i didn't understand :(
we can use `@ember-decoratores/argument` **now** with **typescript** or not ?
the only feature that i need is to check if an argument has been passed or not(i don't need the type checking), for example:
```ts
export default class MyLink extends Component {
  @argument
  @required
  href: string;
}
```
the `my-link.hbs`:
```hbs
<a href={{ @href }}>{{ yield }}</a>
```
the `template.hbs`:
```hbs
// throw an error(forget to pass the `href` argument)
<MyLink>About</MyLink>
```
thanks

**Comment by pzuraq** [comment]
Hey @flashios09, you _cannot_ use `@argument` with typescript, and it will never be supported. Instead, we want to integrate Typescript's type checker so that it can read templates, and do type checking through them.

So for instance, if you have the component:

```ts
export default class MyLink extends Component {
  href: string;
}
```

and you attempt to use it like so:

```hbs
<a>{{yield}}</a>
```

Typescript should throw an error because the argument is not used at all, so it is undefined. For optional arguments, you would have to specify `undefined` as a union type:

```ts
export default class MyLink extends Component {
  href: string | undefined;
}
```

**Comment by flashios09** [comment]
hi @pzuraq ,
thanks for your reply
> the only feature that i need is to check if an argument has been passed or not(i don't need the type checking)

for me the decorators make the code **more readable** and that's why i love them, for example when i use the `@className`, `@action` decorator, i don't even have to add a doc:
```ts
// import ... from ...
export default class MyLinkComponent extends Component {
  // this is a class name
  @className
  loading;
 
  // this is another class name
  @className
  active; 
 
  // this is a computed property
  @computed
  get isActive { ... }  

 // this is an action
 @action
 clicked { ... }
 // ...

}
```
the only missing part is the `@argument` decorator, when i said:
```hbs
// throw an error(forget to pass the `href` argument)
<MyLink>About</MyLink>
```
i mean when i forget to pass the `href` argument from **the component invocation**(the route template file or a parent component) not in the **component template** file, i will have an error in the console !
having an argument decorator, it makes the code more readable(for me):
```ts
export default class MyLinkComponent extends Component {
  // this is a component property, it can be anything
  href = null;
  
  // this is an argument and it's required 
  // so if i forget to pass it from the component invocation
  // i will have an error in the console
  @argument
  @required
  href;
}
```
