### ISSUE TITLE
Readme does not explain what property needs to be set to turn this off

### ISSUE THREAD

**Issue by JonForest** [ember-decorators/argument#70]
It's tricky to apply this progressively to an existing project as you need to set a value in `config/environment.js` in order to stop all your components throwing validation errors.

Looking through the code it looks like you need
```
module.exports = function (environment) {
  let ENV = {
    ...
    '@ember-decorators/argument.ignoreComponentsWithoutValidations': true,
    ...
```

I'll try to raise a PR for this if you're interested and I've understood correctly, though this does work.

**Comment by pzuraq** [comment]
yeah, that is the configuration option that's required. Would definitely appreciate a PR for the README, it's been on my to do list but haven't had a chance to get to it yet!

**Comment by pzuraq** [comment]
Ah actually, minor clarification - I believe it's meant to be a nested object there:

```js
module.exports = function (environment) {
  let ENV = {
    ...
    '@ember-decorators/argument': {
      ignoreComponentsWithoutValidations: true,
    },
    ...
```

**Comment by JonForest** [comment]
And looking at the readme again I see this instruction RIGHT THERE.  I must have been blind first time.
I can add a PR to include the code example - if you think it's helpful, feel free to merge.

**Comment by pzuraq** [comment]
I think the code example would be easier to read and parse, you probably missed it because it's all headers and such 😛 no worries, it happens

**Comment by JonForest** [comment]
PR merged on this, so closing.
