### ISSUE TITLE
Babel 7 Support

### ISSUE THREAD

**Issue by alexlafroscia** [ember-decorators/argument#75]
With `ember-cli-babel@7` released, the Ember community has access to Babel 7!

At this time, this addon is not configured to work with anything other than a `6.X.X` release of `ember-cli-babel`. I'm not sure if the API has changed in a breaking way or if the restraint just has to be updated here, but either way compatibility should be provided.

(Just like https://github.com/ember-decorators/babel-transforms/issues/12 I will investigate fixing this one, too!)

**Comment by alexlafroscia** [comment]
Looking into this a bit, we would need to upgrade to the latest version of `babel-plugin-filter-imports`, which is for Babel 7.

Since it's the same package, but a newer version, I'm not sure how we would maintain support for both Babel 6 _and_ Babel 7 when this underlying package is for only one or the other. I did look into installing both versions with alternate names, but couldn't find a way that's actually supported by NPM to do that.

How would you feel about cutting a "breaking change" (which I know isn't real since this package hasn't hit `1.0` yet) that requires Babel 7, and point people toward an older release for Babel 6 compatibility?

cc: @pzuraq @rwjblue

**Comment by pzuraq** [comment]
I think that would be good. Now that the native class constructor update RFC has been merged this addon will be changed to be 100% validation decorators that are all stripped in production builds, so I think we should first cut a Babel 7 compatible release for users on older versions of Ember, and then make the switch to validation-only once the work has been completed in Ember core.

**Comment by alexlafroscia** [comment]
> I think that would be good

Sweet! In that case, I'll put together a PR tomorrow that upgrades to Babel 7 compatibility.

> then make the switch to validation-only once the work has been completed in Ember core.

What do you mean? What more than validation is being done right now?

**Comment by alexlafroscia** [comment]
With `^` that issue closed, I'm going to take a look at finishing this

**Comment by alexlafroscia** [comment]
Alright, so the failures here are due to issues that happen on `master` as well as this branch.

I'll see if I can get that passing, so that this PR can finally land.

**Comment by Devoter** [comment]
Ember 3.6.0 released with babel 7.
